zed:
  - changed-files:
      - any-glob-to-any-file: ['bundles/**/src/FondOfKudu/Zed/**']

yves:
  - changed-files:
      - any-glob-to-any-file: ['bundles/**/src/FondOfKudu/Yves/**']

glue:
  - changed-files:
      - any-glob-to-any-file: ['bundles/**/src/FondOfKudu/Glue/**']

client:
  - changed-files:
      - any-glob-to-any-file: ['bundles/**/src/FondOfKudu/Client/**']

service:
  - changed-files:
      - any-glob-to-any-file: ['bundles/**/src/FondOfKudu/Service/**']

tests:
  - changed-files:
      - any-glob-to-any-file: ['bundles/**/tests/FondOfKudu/**']

composer:
  - changed-files:
      - any-glob-to-any-file: ['composer.json', 'bundles/**/src/FondOfKudu/composer.json']

github:
  - changed-files:
      - any-glob-to-any-file: ['.github/**']

version:
  - changed-files:
      - any-glob-to-any-file: ['dandelion.json']

### packages

carts-rest-api:
  - changed-files:
      - any-glob-to-any-file: ['bundles/carts-rest-api/**']

catalog-sort-price:
  - changed-files:
      - any-glob-to-any-file: ['bundles/catalog-sort-price/**']

checkout-rest-api:
  - changed-files:
      - any-glob-to-any-file: ['bundles/checkout-rest-api/**']

checkout-rest-api-country-connector:
  - changed-files:
      - any-glob-to-any-file: ['bundles/checkout-rest-api-country-connector/**']

checkout-rest-api-country-extension:
  - changed-files:
      - any-glob-to-any-file: ['bundles/checkout-rest-api-country-extension/**']

product-image-storage-connector:
  - changed-files:
      - any-glob-to-any-file: ['bundles/product-image-storage-connector/**']

quote:
  - changed-files:
      - any-glob-to-any-file: ['bundles/quote/**']

country-zipcode-restriction:
  - changed-files:
      - any-glob-to-any-file: ['bundles/country-zipcode-restriction/**']

checkout-data-product-country-filter:
  - changed-files:
      - any-glob-to-any-file: ['bundles/checkout-data-product-country-filter/**']

checkout-data-gift-cart-payment-country-filter:
  - changed-files:
      - any-glob-to-any-file: ['bundles/checkout-data-gift-cart-payment-country-filter/**']

oms-order-confirmation:
  - changed-files:
      - any-glob-to-any-file: ['bundles/oms-order-confirmation/**']

oms-payone-error:
  - changed-files:
      - any-glob-to-any-file: ['bundles/oms-payone-error/**']

oms-retry-capture-process:
  - changed-files:
      - any-glob-to-any-file: ['bundles/oms-retry-capture-process/**']

discount-promotion-rest-api:
  - changed-files:
      - any-glob-to-any-file: ['discount-promotion-rest-api/**']
