zed:
  - changed-files:
      - any-glob-to-any-file: ['bundles/**/src/FondOfKudu/Zed/**']

yves:
  - changed-files:
      - any-glob-to-any-file: ['bundles/**/src/FondOfKudu/Yves/**']

glue:
  - changed-files:
      - any-glob-to-any-file: ['bundles/**/src/FondOfKudu/Glue/**']

client:
  - changed-files:
      - any-glob-to-any-file: ['bundles/**/src/FondOfKudu/Client/**']

service:
  - changed-files:
      - any-glob-to-any-file: ['bundles/**/src/FondOfKudu/Service/**']

tests:
  - changed-files:
      - any-glob-to-any-file: ['bundles/**/tests/FondOfKudu/**']

composer:
  - changed-files:
      - any-glob-to-any-file: ['composer.json', 'bundles/**/src/FondOfKudu/composer.json']

github:
  - changed-files:
      - any-glob-to-any-file: ['.github/**']

version:
  - changed-files:
      - any-glob-to-any-file: ['dandelion.json']
