zed:
  - changed-files:
      - any-glob-to-any-file: ['bundles/**/src/FondOfKudu/Zed/**']

yves:
  - changed-files:
      - any-glob-to-any-file: ['bundles/**/src/FondOfKudu/Yves/**']

glue:
  - changed-files:
      - any-glob-to-any-file: ['bundles/**/src/FondOfKudu/Glue/**']

client:
  - changed-files:
      - any-glob-to-any-file: ['bundles/**/src/FondOfKudu/Client/**']

service:
  - changed-files:
      - any-glob-to-any-file: ['bundles/**/src/FondOfKudu/Service/**']

tests:
  - changed-files:
      - any-glob-to-any-file: ['bundles/**/tests/FondOfKudu/**']

composer:
  - changed-files:
      - any-glob-to-any-file: ['composer.json', 'bundles/**/src/FondOfKudu/composer.json']

github:
  - changed-files:
      - any-glob-to-any-file: ['.github/**']

version:
  - changed-files:
      - any-glob-to-any-file: ['dandelion.json']

### packages

carts-rest-api:
  - changed-files:
      - any-glob-to-any-file: ['bundles/carts-rest-api/**']

checkout-rest-api:
  - changed-files:
      - any-glob-to-any-file: ['bundles/checkout-rest-api/**']

checkout-rest-api-country-connector:
  - changed-files:
      - any-glob-to-any-file: ['bundles/checkout-rest-api-country-connector/**']

checkout-rest-api-country-extension:
  - changed-files:
      - any-glob-to-any-file: ['bundles/checkout-rest-api-country-extension/**']

quote:
  - changed-files:
      - any-glob-to-any-file: ['bundles/quote/**']

country-zipcode-restriction:
  - changed-files:
      - any-glob-to-any-file: ['bundles/country-zipcode-restriction/**']
