<?php

namespace Zed\CustomerPasswordUpdatedAtConnector\Persistence;

use Spryker\Zed\Kernel\Persistence\AbstractEntityManager;

class CustomerPasswordUpdatedAtConnectorEntityManager extends AbstractEntityManager implements CustomerPasswordUpdatedAtConnectorEntityManagerInterface
{
}
